# Site settings
name: invlong's Blog
email: pro.invlong@gmail.com
author: invlong
url: https://invlong.github.io/
resume_site: https://github.com/invlong
github: https://github.com/invlong
baseurl: ""
description: I’ll protect you.All you gotta do is  take this pocket right here.
meta_description: 吴晓龙;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: invlong

# Build settings
markdown: kramdown
toc_levels: 1..3
baidu_analysis: 48eaa92995fa9a1b400d90b56de84b4c

